package uk.gov.moj.cpp.progression.domain.constant;

public enum NotificationStatus {
    AWAITING_GENERATION, GENERATION_REQUESTED, ATTACHED, NOTIFICATION_REQUEST, NOTIFICATION_REQUEST_FAILED, NOTIFICATION_REQUEST_NOT_SENT, NOTIFICATION_REQUEST_SUCCEEDED, NOTIFICATION_REQUEST_ACCEPTED
}
