#%RAML 0.8
title: Progression Query API
baseUri: http://localhost:8080/progression-query-api/query/api/rest/progression
protocols: [ HTTP, HTTPS ]
                       
/cases/{caseId}:
  uriParameters:
        caseId:
          description: ID of case to get
          type: string
  get:
      description: |
        Return the case progression details for the case Id.
        ...
        (mapping):
            responseType: application/vnd.progression.query.caseprogressiondetail+json
            name: progression.query.caseprogressiondetail
        ...
      responses:
            200:
                description: OK        
                body: 
                  application/vnd.progression.query.caseprogressiondetail+json:
                    example:  !include json/progression.query.caseprogressiondetail.json
                    schema:  !include json/schema/progression.query.caseprogressiondetail.json
                    
/cases/{caseId}/timeline:
  uriParameters:
        caseId:
          description: ID of case to get
          type: string
  get:
      description: |
        Timeline (progression date's) for the case progression detail
        ...
        (mapping):
            responseType: application/vnd.progression.query.timeline+json
            name: progression.query.timeline
        ...
      responses:
            200:
                description: OK        
                body:
                  application/vnd.progression.query.timeline+json: 
                      example: !include json/progression.query.timeline.json
                      schema: !include json/schema/progression.query.timeline.json
                        
/cases/{caseId}/indicatestatements:
  uriParameters:
        caseId:
          description: ID of case to get
          type: string
  get:
      description: |
        List of indicatestatements for the case.
        ...
        (mapping):
            responseType: application/vnd.progression.query.indicatestatementsdetails+json
            name: progression.query.indicatestatementsdetails
        ...
      responses:
            200:
                description: OK        
                body:
                  application/vnd.progression.query.indicatestatementsdetails+json: 
                      example: !include json/progression.query.indicatestatementsdetails.json
                      schema: !include json/schema/progression.query.indicatestatementsdetails.json   
                                           
                       
/indicatestatement/{indicatestatementId}:
  uriParameters:
        indicatestatementId:
          description: ID of indicatestatement to get
          type: string
  get:
      description: |
        Indicatestatement for the indicatestatementId.
        ...
        (mapping):
            responseType: application/vnd.progression.query.indicatestatementsdetail+json
            name: progression.query.indicatestatementsdetail
        ...
      responses:
            200:
                description: OK        
                body:
                  application/vnd.progression.query.indicatestatementsdetail+json: 
                      example: !include json/progression.query.indicatestatementsdetail.json
                      schema: !include json/schema/progression.query.indicatestatementsdetail.json
                       

/cases:
  get:
      description: |
        List of case progression details
        ...
        (mapping):
            responseType: application/vnd.progression.query.cases+json
            name: progression.query.cases
        ...
      queryParameters:
        status:
          description: comma separated list of case status ex ?status=xxx,yyy
          type: string
          example: xxx,yyy
          required: false
      responses:
            200:
                description: OK        
                body: 
                  application/vnd.progression.query.cases+json:
                    example:  !include json/progression.query.cases.json
                    schema:  !include json/schema/progression.query.cases.json
