#%RAML 0.8
title: Progression Command API
version: 1.0
baseUri:  http://localhost:8080/progression-command-api/command/api/rest/progression


/cases/sendcasetocrowncourt:
  post:
      description: |
        Case is sent to a Crown Court for Hearing by a Magistrates Court
        ...
        (mapping):
            requestType: application/vnd.progression.command.send-to-crown-court+json
            name: progression.command.send-to-crown-court
        ...
      body:
        application/vnd.progression.command.send-to-crown-court+json:
            example: 
             !include json/progression.command.send-to-crown-court.json          
             
            schema: 
             !include json/schema/progression.command.send-to-crown-court.json
              
      responses:
            202:
                description: OK
                
/cases/addcasetocrowncourt:
  post:
      description: |
        Case is sent to a Crown Court for Hearing by a Magistrates Court,The Case is identified on the Common Platform  and added to appropriate Crown Court 
        ...
        (mapping):
            requestType: application/vnd.progression.command.add-case-to-crown-court+json
            name: progression.command.add-case-to-crown-court
        ...
      body:
        application/vnd.progression.command.add-case-to-crown-court+json:
            example: 
             !include json/progression.command.add-case-to-crown-court.json          
             
            schema: 
             !include json/schema/progression.command.add-case-to-crown-court.json
              
      responses:
            202:
                description: OK                
                
/cases/adddefenceissues:
  post:
      description: |
        Add Defence Issues to the Case
        ... 
        (mapping):
            requestType: application/vnd.progression.command.add-defence-issues+json
            name: progression.command.add-defence-issues
        ...
      body:
        application/vnd.progression.command.add-defence-issues+json:
            example: 
             !include json/progression.command.add-defence-issues.json         
             
            schema: 
             !include json/schema/progression.command.add-defence-issues.json
              
      responses:
            202:
                description: OK
                
/cases/sentencehearingdate :
  post:
      description: |
        Add sentence hearing date.
        ...
        (mapping):
            requestType: application/vnd.progression.command.sentence-hearing-date+json
            name: progression.command.sentence-hearing-date
        ...
      body:
        application/vnd.progression.command.sentence-hearing-date+json:
            example: 
             !include json/progression.command.sentence-hearing-date.json         
             
            schema: 
             !include json/schema/progression.command.sentence-hearing-date.json
              
      responses:
            202:
                description: OK    
                
/cases/addsfrissues:
  post:
      description: |
        Add issues with Streamlined Forensics Report
        ...
        (mapping):
            requestType: application/vnd.progression.command.addsfrissues+json
            name: progression.command.addsfrissues
        ...
      body:
        application/vnd.progression.command.addsfrissues+json:
            example: 
             !include json/progression.command.addsfrissues.json         
             
            schema: 
             !include json/schema/progression.command.addsfrissues.json
              
      responses:
            202:
                description: OK   
                
/cases/sendingcommittalhearinginformation:
  post:
      description:  |
        sending committal hearing information to be added to the case
        ...
        (mapping):
            requestType: application/vnd.progression.command.sending-committal-hearing-information+json
            name: progression.command.sending-committal-hearing-information
        ...
      body:
        application/vnd.progression.command.sending-committal-hearing-information+json:
            example: 
             !include json/progression.command.sending-committal-hearing-information.json         
             
            schema: 
             !include json/schema/progression.command.sending-committal-hearing-information.json
              
      responses:
            202:
                description: OK                 

/cases/defencetrialestimate:
  post:
      description: |
        Add trail estimate required for hearing given by the defence
        ...
        (mapping):
            requestType: application/vnd.progression.command.defence-trial-estimate+json
            name: progression.command.defence-trial-estimate
        ...
      body:
        application/vnd.progression.command.defence-trial-estimate+json:
            example: 
             !include json/progression.command.defence-trial-estimate.json         
             
            schema: 
             !include json/schema/progression.command.defence-trial-estimate.json
              
      responses:
            202:
                description: OK    

/cases/issuedirection:
  post:
      description:  |
        Add direction issued by the judge
        ...
        (mapping):
            requestType: application/vnd.progression.command.issue-direction+json
            name: progression.command.issue-direction
        ...
      body:
        application/vnd.progression.command.issue-direction+json:
            example: 
             !include json/progression.command.issue-direction.json         
             
            schema: 
             !include json/schema/progression.command.issue-direction.json
              
      responses:
            202:
                description: OK  
                
/cases/presentencereport:
  post:
      description: |
        Add pre scentence reports
        ...
        (mapping):
            requestType: application/vnd.progression.command.pre-sentence-report+json
            name: progression.command.pre-sentence-report
        ...
      body:
        application/vnd.progression.command.pre-sentence-report+json:
            example: 
             !include json/progression.command.pre-sentence-report.json         
             
            schema: 
             !include json/schema/progression.command.pre-sentence-report.json
              
      responses:
            202:
                description: OK                                                         

/cases/indicatestatement:
  post:
      description: |
        Add indicatestatement for thee case
        ...
        (mapping):
            requestType: application/vnd.progression.command.indicate-statement+json
            name: progression.command.indicate-statement
        ...
      body:
        application/vnd.progression.command.indicate-statement+json:
            example: 
             !include json/progression.command.indicate-statement.json         
             
            schema: 
             !include json/schema/progression.command.indicate-statement.json
              
      responses:
            202:
                description: OK                  
                
/cases/indicateallstatementsidentified:
  post:
      description:  |
        indicate that all statements has been identified 
        ...
        (mapping):
            requestType: application/vnd.progression.command.indicate-all-statements-identified+json
            name: progression.command.indicate-all-statements-identified
        ...
      body:
        application/vnd.progression.command.indicate-all-statements-identified+json:
            example: 
             !include json/progression.command.indicate-all-statements-identified.json         
             
            schema: 
             !include json/schema/progression.command.indicate-all-statements-identified.json
              
      responses:
            202:
                description: OK   
                             
/cases/indicateallstatementsserved:
  post:
      description:  |
        indicate that all statements has been served
        ...
        (mapping):
            requestType: application/vnd.progression.command.indicate-all-statements-served+json
            name: progression.command.indicate-all-statements-served
        ...
      body:
        application/vnd.progression.command.indicate-all-statements-served+json:
            example: 
             !include json/progression.command.indicate-all-statements-served.json         
             
            schema: 
             !include json/schema/progression.command.indicate-all-statements-served.json
              
      responses:
            202:
                description: OK           
                                         
/cases/prosecutiontrialestimate:
  post:
      description:   |
        Add trail estimate required for hearing given by the prosecution
        ...
        (mapping):
            requestType: application/vnd.progression.command.prosecution-trial-estimate+json
            name: progression.command.prosecution-trial-estimate
        ...
      body:
        application/vnd.progression.command.prosecution-trial-estimate+json:
            example: 
             !include json/progression.command.prosecution-trial-estimate.json         
             
            schema: 
             !include json/schema/progression.command.prosecution-trial-estimate.json
              
      responses:
            202:
                description: OK                                             
    
/cases/vacateptphearing:
  post:
      description: |
        Vacate the booked PTP Hearing
        ...
        (mapping):
            requestType: application/vnd.progression.command.vacate-ptp-hearing+json
            name: progression.command.vacate-ptp-hearing
        ...
      body:
        application/vnd.progression.command.vacate-ptp-hearing+json:
            example: 
             !include json/progression.command.vacate-ptp-hearing.json         
             
            schema: 
             !include json/schema/progression.command.vacate-ptp-hearing.json
              
      responses:
            202:
                description: OK

/cases/casetobeassigned:
  post:
      description:  |
        Assign the status Ready for Review which signifies that a case is ready to be assigned to a Judge for Sentencing Hearing Review.
        ...
        (mapping):
            requestType: application/vnd.progression.command.case-to-be-assigned+json
            name: progression.command.case-to-be-assigned
        ...
      body:
        application/vnd.progression.command.case-to-be-assigned+json:
            example: 
             !include json/progression.command.case-to-be-assigned.json         
             
            schema: 
             !include json/schema/progression.command.case-to-be-assigned.json
              
      responses:
            202:
                description: OK                                 
                
/cases/caseassignedforreview:
  post:
      description:  |
        Moves a case with a  to status "Assigned for Review " once the case is referred to a named Judge/Judicial Officer
        ...
        (mapping):
            requestType: application/vnd.progression.command.case-assigned-for-review+json
            name: progression.command.case-assigned-for-review
        ...
      body:
        application/vnd.progression.command.case-assigned-for-review+json:
            example: 
             !include json/progression.command.case-assigned-for-review.json         
             
            schema: 
             !include json/schema/progression.command.case-assigned-for-review.json
              
      responses:
            202:
                description: OK
                
/cases/prepareforsentencehearing:
  post:
      description:  |
        Marks a  case as Ready for Sentencing when a Judge/Judicial Officer following a SHR, confirms the decision 
        ...
        (mapping):
            requestType: application/vnd.progression.command.prepare-for-sentence-hearing+json
            name: progression.command.prepare-for-sentence-hearing
        ...
      body:
        application/vnd.progression.command.prepare-for-sentence-hearing+json:
            example: 
             !include json/progression.command.prepare-for-sentence-hearing.json         
             
            schema: 
             !include json/schema/progression.command.prepare-for-sentence-hearing.json
              
      responses:
            202:
                description: OK

/caseprogression/{caseProgressionId}/defendantprogression/{defendantProgressionId}:
  uriParameters:
    caseProgressionId:
      description: The ID of the case progression
      type: string
    defendantProgressionId:
      description: The ID of the defendant progression
      type: string
  post:
      description:  |
        the defendant progression details
        ...
        (mapping):
            requestType: application/vnd.progression.command.add-defendant-additional-information+json
            name: progression.command.add-defendant-additional-information
        ...
      body:
        application/vnd.progression.command.add-defendant-additional-information+json:
            example:
             !include json/progression.command.add-defendant-additional-information.json

            schema:
             !include json/schema/progression.command.add-defendant-additional-information.json

      responses:
            202:
                description: OK