#%RAML 0.8
title: API Using media type in the URL
baseUri: message://event/listener/message/progression
version: v1



/progression.event:
  post:
    body:
        application/vnd.progression.event.prosecution-case-created+json:
            schema: !include json/schema/progression.event.prosecution-case-created.json
            example: !include json/progression.event.prosecution-case-created.json

        application/vnd.progression.event.court-document-removed+json:
            schema: !include json/schema/progression.event.court-document-removed.json
            example: !include json/progression.event.court-document-removed.json

        application/vnd.progression.event.court-document-created+json:
            schema: !include json/schema/progression.event.court-document-created.json
            example: !include json/progression.event.court-document-created.json

        application/vnd.progression.event.defendant-request-created+json:
            example: !include json/progression.event.defendant-request-created.json
            schema: !include json/schema/progression.event.defendant-request-created.json

        application/vnd.progression.event.prosecution-case-defendant-updated+json:
            schema: !include json/schema/progression.event.prosecution-case-defendant-updated.json
            example: !include json/progression.event.prosecution-case-defendant-updated.json

        application/vnd.progression.event.prosecution-case-offences-updated+json:
            schema: !include json/schema/progression.event.prosecution-case-offences-updated.json
            example: !include json/progression.event.prosecution-case-offences-updated.json

        application/vnd.progression.event.nows-material-status-updated+json:
            schema: !include json/schema/progression.event.nows-material-status-updated.json
            example: !include json/progression.event.nows-material-status-updated.json

        application/vnd.progression.event.prosecutionCase-defendant-listing-status-changed+json:
            schema: !include json/schema/progression.event.prosecutionCase-defendant-listing-status-changed.json
            example: !include json/progression.event.prosecutionCase-defendant-listing-status-changed.json

        application/vnd.progression.event.prosecutionCase-defendant-hearing-result-updated+json:
            schema: !include json/schema/progression.event.prosecutionCase-defendant-hearing-result-updated.json
            example: !include json/progression.event.prosecutionCase-defendant-hearing-result-updated.json

        application/vnd.progression.event.print-requested+json:
            schema: !include json/schema/progression.event.print-requested.json
            example: !include json/progression.event.print-requested.json

        application/vnd.progression.event.email-requested+json:
            schema: !include json/schema/progression.event.email-requested.json
            example: !include json/progression.event.email-requested.json

        application/vnd.progression.event.notification-request-failed+json:
            schema: !include json/schema/progression.event.notification-request-failed.json
            example: !include json/progression.event.notification-request-failed.json

        application/vnd.progression.event.notification-request-succeeded+json:
            schema: !include json/schema/progression.event.notification-request-succeeded.json
            example: !include json/progression.event.notification-request-succeeded.json

        application/vnd.progression.event.notification-request-accepted+json:
            schema: !include json/schema/progression.event.notification-request-accepted.json
            example: !include json/progression.event.notification-request-accepted.json

        application/vnd.progression.event.hearing-resulted+json:
            schema: !include json/schema/progression.event.hearing-resulted.json
            example: !include json/progression.event.hearing-resulted.json

        application/vnd.progression.event.court-application-created+json:
            schema: !include json/schema/progression.event.court-application-created.json
            example: !include json/progression.event.court-application-created.json

        application/vnd.progression.event.court-application-status-changed+json:
            schema: !include json/schema/progression.event.court-application-status-changed.json
            example: !include json/progression.event.court-application-status-changed.json

        application/vnd.progression.event.court-application-updated+json:
            schema: !include json/schema/progression.event.court-application-updated.json
            example: !include json/progression.event.court-application-updated.json
        application/vnd.progression.event.hearing-application-link-created+json:
            schema: !include json/schema/progression.event.hearing-application-link-created.json
            example: !include json/progression.event.hearing-application-link-created.json

        application/vnd.progression.event.defendants-added-to-court-proceedings+json:
            schema: !include json/schema/progression.event.defendants-added-to-court-proceedings.json
            example: !include json/progression.event.defendants-added-to-court-proceedings.json
        ############  Association Start ############
        application/vnd.progression.event.defence-organisation-associated+json:
            schema: !include json/schema/progression.event.defence-organisation-associated.json
            example: !include json/progression.event.defence-organisation-associated.json
        application/vnd.progression.event.defence-organisation-disassociated+json:
            schema: !include json/schema/progression.event.defence-organisation-disassociated.json
            example: !include json/progression.event.defence-organisation-disassociated.json
        ############  Association End ############

        application/vnd.progression.event.financial-means-deleted+json:
            schema: !include json/schema/progression.event.financial-means-deleted.json
            example: !include json/progression.event.financial-means-deleted.json

        application/vnd.progression.event.hearing-resulted-case-updated+json:
            schema: !include json/schema/progression.event.hearing-resulted-case-updated.json
            example: !include json/progression.event.hearing-resulted-case-updated.json

        application/vnd.progression.event.case-ejected+json:
            schema: !include json/schema/progression.event.case-ejected.json
            example: !include json/progression.event.case-ejected.json

        application/vnd.progression.event.application-ejected+json:
            schema: !include json/schema/progression.event.application-ejected.json
            example: !include json/progression.event.application-ejected.json

        application/vnd.progression.event.boxwork-assignment-changed+json:
            schema: !include json/schema/progression.event.boxwork-assignment-changed.json
            example: !include json/progression.event.boxwork-assignment-changed.json

        application/vnd.progression.event.case-markers-updated+json:
            schema: !include json/schema/progression.event.case-markers-updated.json
            example: !include json/progression.event.case-markers-updated.json

# ***** Deprecated API - Start ********
# ***** Do not add any new API in this section *****

        application/vnd.progression.events.case-added-to-crown-court+json:
            schema: !include json/schema/progression.events.case-added-to-crown-court.json
            example: !include json/progression.events.case-added-to-crown-court.json

        application/vnd.progression.events.sending-committal-hearing-information-added+json:
            schema: !include json/schema/progression.events.sending-committal-hearing-information-added.json
            example: !include json/progression.events.sending-committal-hearing-information-added.json

        application/vnd.progression.events.sentence-hearing-date-added+json:
            schema: !include json/schema/progression.events.sentence-hearing-date-added.json
            example: !include json/progression.events.sentence-hearing-date-added.json            
        
        application/vnd.progression.events.case-to-be-assigned-updated+json:
            schema: !include json/schema/progression.events.case-to-be-assigned-updated.json
            example: !include json/progression.events.case-to-be-assigned-updated.json            
            
        application/vnd.progression.events.case-ready-for-sentence-hearing+json:
            example: !include json/progression.events.case-ready-for-sentence-hearing.json         
            schema:  !include json/schema/progression.events.case-ready-for-sentence-hearing.json
            
        application/vnd.progression.events.case-pending-for-sentence-hearing+json:
            example: !include json/progression.events.case-pending-for-sentence-hearing.json         
            schema:  !include json/schema/progression.events.case-pending-for-sentence-hearing.json
            
        application/vnd.progression.events.defendant-additional-information-added+json:
            example: !include json/progression.events.defendant-additional-information-added.json
            schema:  !include json/schema/progression.events.defendant-additional-information-added.json

        application/vnd.progression.events.no-more-information-required+json:
            example: !include json/progression.events.no-more-information-required.json
            schema:  !include json/schema/progression.events.no-more-information-required.json

        application/vnd.progression.events.pre-sentence-report-for-defendants-requested+json:
            example: !include json/progression.events.pre-sentence-report-for-defendants-requested.json
            schema:  !include json/schema/progression.events.pre-sentence-report-for-defendants-requested.json

        application/vnd.progression.events.offences-for-defendant-updated+json:
            schema: !include json/schema/progression.events.offences-for-defendant-updated.json
            example: !include json/progression.events.offences-for-defendant-updated.json

        application/vnd.progression.events.defendant-added+json:
            schema: !include json/schema/progression.events.defendant-added.json
            example: !include json/progression.events.defendant-added.json

        application/vnd.progression.events.defendant-updated+json:
            schema: !include json/schema/progression.events.defendant-updated.json
            example: !include json/progression.events.defendant-updated.json

        application/vnd.progression.events.sending-sheet-completed+json:
            schema: !include json/schema/progression.events.sending-sheet-completed.json
            example: !include json/progression.events.sending-sheet-completed.json
            
        application/vnd.progression.event.conviction-date-added+json:
            schema: !include json/schema/progression.event.conviction-date-added.json
            example: !include json/progression.event.conviction-date-added.json

        application/vnd.progression.event.conviction-date-removed+json:
            schema: !include json/schema/progression.event.conviction-date-removed.json
            example: !include json/progression.event.conviction-date-removed.json

# Deprecated API  - End
