package uk.gov.moj.cpp.progression.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import uk.gov.moj.cpp.progression.command.api.accesscontrol.RuleConstants;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - Rule for update defendant for prosecution case"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.update-defendant-for-prosecution-case");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Crown Court Admin", "Listing Officers", "Court Administrators", "Legal Advisers" , "Probation Admin", "Court Associate"));
  then
    $outcome.setSuccess(true);
end

rule "Command - Rule for update master defendant for prosecution case"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.update-master-defendant");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users"));
  then
    $outcome.setSuccess(true);
end
