package uk.gov.moj.cpp.progression.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - resend laa outcome concluded by bdf"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.resend-laa-outcome-concluded");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users"));
  then
    $outcome.setSuccess(true);
end



