package uk.gov.moj.cpp.progression.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - Access control for progression.command.defendant-document"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.defendant-document");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Crown Court Admin", "Listing Officers", "Court Clerks", "Court Administrators", "Legal Advisers", "Court Associate"))
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - progression.generate-nows"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.generate-nows");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "System Users", "Court Associate"));
  then
    $outcome.setSuccess(true);
end

rule "Command - Access control for progression.update-civil-fees"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.update-civil-fees");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Crown Court Admin", "Listing Officers", "Court Clerks", "Court Administrators", "Legal Advisers", "Court Associate", "CTSC Admin"))
  then
    $outcome.setSuccess(true);
end
