package uk.gov.moj.cpp.progression.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import uk.gov.moj.cpp.progression.command.api.accesscontrol.PermissionConstants;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - Rule for intitiate court proceedings for application"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.initiate-court-proceedings-for-application");
    eval(userAndGroupProvider.hasPermission($action, PermissionConstants.getCaseCreatePermission())) or
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, PermissionConstants.getUsersForCourtProceedingsForApplication()));
  then
    $outcome.setSuccess(true);
end



