package uk.gov.moj.cpp.progression.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;

rule "Command - Create Aaag HearingEventLogDocument"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.create-aaag-hearing-event-log-document");
    eval($action.userId().isPresent());
  then
    $outcome.setSuccess(true);
end