package uk.gov.moj.cpp.progression.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - update listing number"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.update-listing-number");
    eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end



