package uk.gov.moj.cpp.progression.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - Rule for list new hearing"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.list-new-hearing");
    eval(userAndGroupProvider.hasPermission($action, PermissionRuleConstants.adhocHearingCreatePermission()));
  then
    $outcome.setSuccess(true);
end



