package uk.gov.moj.cpp.progression.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - API - Action - progression.correct-hearing-days-without-court-centre"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.correct-hearing-days-without-court-centre");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users" ));
  then
    $outcome.setSuccess(true);
end
