package uk.gov.moj.cpp.progression.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - Rule for Record LAA Reference for Application"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.record-laareference-for-application");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users" ));
  then
    $outcome.setSuccess(true);
end

rule "Command - Rule for Record LAA Reference for Application on Application"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.record-laareference-for-application-on-application");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users" ));
  then
    $outcome.setSuccess(true);
end
