package uk.gov.moj.cpp.progression.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - remove deleted hearing child entries by bdf"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.remove-deleted-hearing-child-entries-bdf");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users"));
  then
    $outcome.setSuccess(true);
end

rule "Command - remove duplicate application from hearing by bdf"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.remove-duplicate-application-bdf");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users"));
  then
    $outcome.setSuccess(true);
end



