#%RAML 0.8
title: Progression Query view
baseUri: http://localhost:8080/progression-query-view/query/view/rest/progression
protocols: [ HTTP, HTTPS ]

/material/{materialId}/metadata1:
  description: get  material metadata
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.progression.query.material-metadata+json
          name: progression.query.material-metadata1
      ...
    responses:
      200:
        body:
          application/vnd.progression.query.material-metadata+json:
            schema: !include json/schema/progression.query.material-metadata.json
            example: !include json/progression.query.material-metadata.json

/prosecutioncases/{caseId}:
  uriParameters:
        caseId:
          description: ID of prosecution case to get
          type: string
  get:
      description: |
        Return the case progression details for the prosecution case Id.
        ...
        (mapping):
            responseType: application/vnd.progression.query.prosecutioncase+json
            name: progression.query.prosecutioncase
        (mapping):
            responseType: application/vnd.progression.query.prosecutioncase.caag+json
            name: progression.query.prosecutioncase.caag
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.progression.query.prosecutioncase+json:
                    example:  !include json/progression.query.prosecutioncase.json
                    schema:  !include json/schema/progression.query.prosecutioncase.json
                  application/vnd.progression.query.prosecutioncase.caag+json:
                    example:  !include json/progression.query.prosecutioncase.caag.json
                    schema:  !include json/schema/progression.query.prosecutioncase.caag.json

/defendant-requests/{defendantId}:
  uriParameters:
        defendantId:
          description: ID of defendant to get request details
          type: string
  get:
      description: |
        Return the defendant request details that is originally part of court referral request.
        ...
        (mapping):
            responseType: application/vnd.progression.query.defendant-request+json
            name: progression.query.defendant-request
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.progression.query.defendant-request+json:
                    example:  !include json/progression.query.defendant-request.json
                    schema:  !include json/schema/progression.query.defendant-request.json

/courtdocuments/{courtDocumentId}:
  uriParameters:
        courtDocumentId:
          description: ID of court document to get
          type: string
  get:
      description: |
        Return the court document details for the  Id.
        ...
        (mapping):
            responseType: application/vnd.progression.query.courtdocument+json
            name: progression.query.courtdocument
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.progression.query.courtdocument+json:
                    example:  !include json/progression.query.courtdocument.json
                    schema:  !include json/schema/progression.query.courtdocument.json

/courtdocumentsearch:
  get:
      description: |
        Search for court documentIndices.
        ...
        (mapping):
            responseType: application/vnd.progression.query.courtdocuments+json
            name: progression.query.courtdocuments
        ...
      queryParameters:
              caseId:
                description: caseId(s) - comma separated to be searched
                type: string
                example: b44fa9bb-dc36-4375-83a9-ff1bc4cd4374,1f1fba3c-34ee-454e-b3be-5fb845b2de4a
                required: false
              defendantId:
                description: defendant id to be searched
                type: string
                example: b44fa9bb-dc36-4375-83a9-ff1bc4cd4374,1f1fba3c-34ee-454e-b3be-5fb845b2de4a
                required: false
              applicationId:
                description: application id (s) - comma separated to be searched
                type: string
                example: b44fa9bb-dc36-4375-83a9-ff1bc4cd4374,1f1fba3c-34ee-454e-b3be-5fb845b2de4a
                required: false

      responses:
            200:
                description: OK
                body:
                  application/vnd.progression.query.courtdocuments+json:
                    example:  !include json/progression.query.courtdocuments.json
                    schema:  !include json/schema/progression.query.courtdocuments.json

/search:
  get:
      description: |
        Search for cases
        ...
        (mapping):
            responseType: application/vnd.progression.query.search-cases+json
            name: progression.query.search-cases
        (mapping):
            responseType: application/vnd.progression.query.cases-search-by-material-id+json
            name: progression.query.cases-search-by-material-id
        (mapping):
            responseType: application/vnd.progression.query.usergroups-by-material-id+json
            name: progression.query.usergroups-by-material-id
        ...
      queryParameters:
        q:
          description: space separated list of search parameters
          type: string
          example: first name last name
          required: false

      responses:
            200:
                description: OK
                body:
                  application/vnd.progression.query.search-cases+json:
                    example: !include json/progression.query.search-cases.json
                    schema: !include json/schema/progression.query.search-cases.json
                  application/vnd.progression.query.cases-search-by-material-id+json:
                    example: !include json/progression.query.cases-search-by-material-id.json
                    schema: !include json/schema/progression.query.cases-search-by-material-id.json
                  application/vnd.progression.query.usergroups-by-material-id+json:
                    example:  !include json/progression.query.usergroups-by-material-id.json
                    schema:  !include  json/schema/progression.query.usergroups-by-material-id.json


/applications/{applicationId}:
  uriParameters:
        applicationId:
          description: primary key of application to get
          type: string
  get:
      description: |
        Return application summary for requested application Id.
        Return application details for requested application Id.
        ...
        (mapping):
            responseType: application/vnd.progression.query.application+json
            name: progression.query.application
        (mapping):
            responseType: application/vnd.progression.query.application.summary+json
            name: progression.query.application.summary
        (mapping):
            responseType: application/vnd.progression.query.application.aaag+json
            name: progression.query.application.aaag
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.progression.query.application+json:
                    example:  !include json/progression.query.application.json
                    schema:  !include json/schema/progression.query.application.json
                  application/vnd.progression.query.application.summary+json:
                    example:  !include json/progression.query.application.summary.json
                    schema:  !include json/schema/progression.query.application.summary.json
                  application/vnd.progression.query.application.aaag+json:
                    example:  !include json/progression.query.application.aaag.json
                    schema:  !include json/schema/progression.query.application.aaag.json
/applications/{applicationId}/notification-status:
  description: get notification status for application Id
  uriParameters:
    applicationId:
      description: application Id
      type: string

  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.progression.query.application.notification-status+json
          name: progression.query.application.notification-status
      ...
    responses:
      200:
        body:
          application/vnd.progression.query.application.notification-status+json:
            schema: !include json/schema/progression.query.application.notification-status.json
            example: !include json/progression.query.application.notification-status.json

/hearingSearch/{hearingId}:
  uriParameters:
        hearingId:
          description: ID of hearing to get
          type: string
  get:
      description: |
        Return the hearing details for the  Id.
        ...
        (mapping):
            responseType: application/vnd.progression.query.hearing+json
            name: progression.query.hearing
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.progression.query.hearing+json:
                    example:  !include json/progression.query.hearing.json
                    schema:  !include json/schema/progression.query.hearing.json

/prosecutioncases/{caseId}/notification-status:
  uriParameters:
    caseId:
      description: Case Id
      type: string
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.progression.query.prosecution.notification-status+json
          name: progression.query.prosecution.notification-status
      ...
    responses:
      200:
        body:
          application/vnd.progression.query.prosecution.notification-status+json:
            schema: !include json/schema/progression.query.prosecution.notification-status.json
            example: !include json/progression.query.prosecution.notification-status.json

/defendants/{defendantId}/associatedOrganisations:
  description: get associated defence organisations
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.progression.query.associated-organisation+json
          name: progression.query.associated-organisation
      ...
    responses:
      200:
        body:
          application/vnd.progression.query.associated-organisation+json:
            example:  !include json/progression.query.associated-organisation-details.json
            schema:  !include json/schema/progression.query.associated-organisation-details.json

/cases/{caseId}/notes:
  uriParameters:
        caseId:
          description: ID of case notes to get
          type: string
  get:
      description: |
        Return the case notes for the case Id.
        ...
        (mapping):
            responseType: application/vnd.progression.query.case-notes+json
            name: progression.query.case-notes
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.progression.query.case-notes+json:
                    example:  !include json/progression.query.case-notes.json
                    schema:  !include json/schema/progression.query.case-notes.json

/shareddocuments/{hearingId}:
  description: Return court documents shared for given hearing id
  uriParameters:
    hearingId:
      description: ID of hearing
      type: string

  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.progression.query.shared-court-documents+json
          name: progression.query.shared-court-documents
      ...

    queryParameters:
      userGroupId:
        type: string
        required: false
      caseId:
        type: string
        required: false
      defendantId:
        type: string
        required: false
    responses:
      200:
        body:
          application/vnd.progression.query.shared-court-documents+json:


/defendants/{laaContractNumber}:
   uriParameters:
     laaContractNumber:
       description: LAA Contract Number
       type: string
   get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.progression.query.defendants-by-laacontractnumber+json
          name: progression.query.defendants-by-laacontractnumber
      ...
    responses:
      200:
        body:
          application/vnd.progression.query.defendants-by-laacontractnumber+json:
            example:  !include json/progression.query.defendants-by-laacontractnumber.json
            schema:  !include json/schema/progression.query.defendants-by-laacontractnumber.json

# ***** Deprecated API - Start ********

# ***** Do not add any new API in this section *****
/cases/{caseId}:
  uriParameters:
        caseId:
          description: ID of case to get
          type: string
  get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.progression.query.caseprogressiondetail+json
            name: progression.query.caseprogressiondetail
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.progression.query.caseprogressiondetail+json:
                    example:  !include json/progression.query.caseprogressiondetail.json
                    schema:  !include json/schema/progression.query.caseprogressiondetail.json

/cases:
  get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.progression.query.cases+json
            name: progression.query.cases
         (mapping):
            responseType: application/vnd.progression.query.case-by-urn+json
            name: progression.query.case-by-urn
        ...
      queryParameters:
        status:
          description: comma separated list of case status ex ?status=xxx,yyy
          type: string
          example: xxx,yyy
          required: false
        caseId:
          description: ID of case to search
          type: string
          required: false
        urn:
          description: urn of case to search
          type: string
          required: false
      responses:
            200:
                description: OK
                body:
                  application/vnd.progression.query.cases+json:
                    example:  !include json/progression.query.cases.json
                    schema:  !include json/schema/progression.query.cases.json
                  application/vnd.progression.query.case-by-urn+json:
                    example:  !include json/progression.query.case-by-urn.json
                    schema:  !include json/schema/progression.query.case-by-urn.json

/cases/{caseId}/defendants/{defendantId}:
  uriParameters:
        caseId:
          description: ID of case to get
          type: string
        defendantId:
          description: ID of defendant
          type: string
  get:
      description: |
        Return the defendant progression details for the defendant Id.
        ...
        (mapping):
            responseType: application/vnd.progression.query.defendant+json
            name: progression.query.defendant
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.progression.query.defendant+json:
                    example:  !include json/progression.query.defendant.json
                    schema:  !include json/schema/progression.query.defendant.json

/cases/{caseId}/defendants:
  uriParameters:
        caseId:
          description: ID of case to get
          type: string
  get:
      description: |
        Return the defendants progression details for the case Id.
        ...
        (mapping):
            responseType: application/vnd.progression.query.defendants+json
            name: progression.query.defendants
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.progression.query.defendants+json:
                    example:  !include json/progression.query.defendants.json
                    schema:  !include json/schema/progression.query.defendants.json

/cases/{caseId}/defendant/{defendantId}/offences:
   uriParameters:
     caseId:
       description: The ID of the case
       type: string
     defendantId:
       description: The ID of the defendant
       type: string
   get:
     description: |
       Retrieve offences data information
       ...
       (mapping):
           responseType: application/vnd.progression.query.defendant-offences+json
           name: progression.query.defendant-offences
       ...
     responses:
         200:
           description: OK
           body:
                 application/vnd.progression.query.defendant-offences+json:
                   schema: !include json/schema/progression.query.defendant-offences.json
                   example: !include json/progression.query.defendant-offences.json

# Deprecated API  - End
