package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - Rule for book slots for application"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.book-slots-for-application");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Crown Court Admin", "Listing Officers", "Court Administrators", "Legal Advisers", "Probation Admin", "Court Associate"));
  then
    $outcome.setSuccess(true);
end



