package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - Rule for Request Online Pleas Allocation public list notice"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.request-opa-public-list-notice");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users"));
  then
    $outcome.setSuccess(true);
end
rule "Command - Rule for Request Online Pleas Allocation press list notice"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.request-opa-press-list-notice");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users"));
  then
    $outcome.setSuccess(true);
end
rule "Command - Rule for Request Online Pleas Allocation result list notice"
  when

    $outcome: Outcome();
    $action: Action(name == "progression.request-opa-result-list-notice");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users"));
  then
    $outcome.setSuccess(true);
end
