package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import java.util.Arrays;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;


rule "Command - Access control for progression.command.vacate-ptp-hearing"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.vacate-ptp-hearing");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System-Users",   "I2T-Judiciary-Group")))
  then
    $outcome.setSuccess(true);
end

rule "Command - Access control for progression.command.add-defendant-additional-information"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.add-defendant-additional-information");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System-Users")))
  then
    $outcome.setSuccess(true);
end

rule "Command - Access control for progression.command.prosecution-trial-estimate"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.prosecution-trial-estimate");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System-Users", "I2T-Listing-Officer-Group", "I2T-Judiciary-Group")))
  then
    $outcome.setSuccess(true);
end

rule "Command - Access control for progression.command.prepare-for-sentence-hearing"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.prepare-for-sentence-hearing");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System-Users",  "I2T-Listing-Officer-Group", "I2T-Judiciary-Group")))
  then
    $outcome.setSuccess(true);
end


rule "Command - Access control for progression.command.indicate-statement"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.indicate-statement");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System-Users", "I2T-Court-Operations-Officer-Group", "I2T-Listing-Officer-Group")))
  then
    $outcome.setSuccess(true);
end


rule "Command - Access control for progression.command.indicate-all-statements-served"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.indicate-all-statements-served");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System-Users", "I2T-Court-Operations-Officer-Group", "I2T-Listing-Officer-Group")))
  then
    $outcome.setSuccess(true);
end


rule "Command - Access control for progression.command.indicate-all-statements-identified"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.indicate-all-statements-identified");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System-Users", "I2T-Court-Operations-Officer-Group", "I2T-Listing-Officer-Group")))
  then
    $outcome.setSuccess(true);
end


rule "Command - Access control for progression.command.defendant"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.defendant");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System-Users", "I2T-Court-Operations-Officer-Group", "I2T-Listing-Officer-Group", "I2T-Judiciary-Group")))
  then
    $outcome.setSuccess(true);
end

rule "Command - Access control for progression.command.pre-sentence-report"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.pre-sentence-report");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System-Users",  "I2T-Listing-Officer-Group", "I2T-Judiciary-Group")))
  then
    $outcome.setSuccess(true);
end

rule "Command - Access control for progression.command.issue-direction"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.issue-direction");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System-Users", "I2T-Judiciary-Group")))
  then
    $outcome.setSuccess(true);
end


rule "Command - Access control for progression.command.defence-trial-estimate"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.defence-trial-estimate");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System-Users", "I2T-Listing-Officer-Group", "I2T-Judiciary-Group")))
  then
    $outcome.setSuccess(true);
end


rule "Command - Access control for progression.command.sending-committal-hearing-information"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.sending-committal-hearing-information");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System-Users", "I2T-Court-Operations-Officer-Group", "I2T-Listing-Officer-Group")))
  then
    $outcome.setSuccess(true);
end

rule "Command - Access control for progression.command.case-to-be-assigned"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.case-to-be-assigned");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System-Users", "I2T-Listing-Officer-Group")))
  then
    $outcome.setSuccess(true);
end

rule "Command - Access control for progression.command.case-assigned-for-review"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.case-assigned-for-review");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System-Users", "I2T-Listing-Officer-Group")))
  then
    $outcome.setSuccess(true);
end

rule "Command - Access control for progression.command.addsfrissues"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.addsfrissues");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System-Users")))
  then
    $outcome.setSuccess(true);
end

rule "Command - Access control for progression.command.sentence-hearing-date"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.sentence-hearing-date");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System-Users", "I2T-Court-Operations-Officer-Group", "I2T-Listing-Officer-Group")))
  then
    $outcome.setSuccess(true);
end

rule "Command - Access control for progression.command.add-defence-issues"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.add-defence-issues");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System-Users", "I2T-Court-Operations-Officer-Group", "I2T-Listing-Officer-Group")))
  then
    $outcome.setSuccess(true);
end
rule "Command - Access control for progression.command.add-case-to-crown-court"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.add-case-to-crown-court");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System-Users", "I2T-Court-Operations-Officer-Group", "I2T-Listing-Officer-Group")))
  then
    $outcome.setSuccess(true);
end

rule "Command - Access control for progression.command.send-to-crown-court"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.send-to-crown-court");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System-Users", "I2T-Court-Operations-Officer-Group", "I2T-Listing-Officer-Group")))
  then
    $outcome.setSuccess(true);
end



