package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - associate defence organisation"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.associate-defence-organisation");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Defence Users", "System Users"));
  then
    $outcome.setSuccess(true);
end


