package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import java.util.Arrays;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;



rule "Command - Access control for progression.command.add-defendant-additional-information"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.add-defendant-additional-information");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System Users")))
  then
    $outcome.setSuccess(true);
end

rule "Command - Access control for progression.command.prepare-for-sentence-hearing"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.prepare-for-sentence-hearing");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System Users",  "Listing Officers", "Judiciary")))
  then
    $outcome.setSuccess(true);
end



rule "Command - Access control for progression.command.pre-sentence-report"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.pre-sentence-report");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System Users",  "Listing Officers", "Judiciary")))
  then
    $outcome.setSuccess(true);
end

rule "Command - Access control for progression.command.issue-direction"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.issue-direction");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System Users", "Judiciary")))
  then
    $outcome.setSuccess(true);
end


rule "Command - Access control for progression.command.sending-committal-hearing-information"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.sending-committal-hearing-information");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System Users", "Court Operations Officers", "Listing Officers")))
  then
    $outcome.setSuccess(true);
end

rule "Command - Access control for progression.command.case-to-be-assigned"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.case-to-be-assigned");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("Listing Officers", "Court Operations Officers")))
  then
    $outcome.setSuccess(true);
end

rule "Command - Access control for progression.command.case-assigned-for-review"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.case-assigned-for-review");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System Users", "Listing Officers")))
  then
    $outcome.setSuccess(true);
end


rule "Command - Access control for progression.command.sentence-hearing-date"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.sentence-hearing-date");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System Users", "Court Operations Officers", "Listing Officers")))
  then
    $outcome.setSuccess(true);
end


rule "Command - Access control for progression.command.add-case-to-crown-court"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.command.add-case-to-crown-court");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System Users", "Court Operations Officers", "Listing Officers")))
  then
    $outcome.setSuccess(true);
end





