package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import uk.gov.moj.cpp.progression.command.accesscontrol.PermissionRuleConstants;
global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;


rule "Command - Rule for Add Pet Form"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.create-pet-form");
    eval(userAndGroupProvider.hasPermission($action, PermissionRuleConstants.petFormGrantAccessPermission()));
  then
    $outcome.setSuccess(true);
end

rule "Command - Rule for Update Pet Form"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.update-pet-form");
    eval(userAndGroupProvider.hasPermission($action, PermissionRuleConstants.petFormGrantAccessPermission()));
  then
    $outcome.setSuccess(true);
end

rule "Command - Rule for Update Pet Detail"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.update-pet-detail");
    eval(userAndGroupProvider.hasPermission($action, PermissionRuleConstants.petFormGrantAccessPermission()));
  then
    $outcome.setSuccess(true);
end

rule "Command - Rule for finalise Pet Form"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.finalise-pet-form");
    eval(userAndGroupProvider.hasPermission($action, PermissionRuleConstants.petFormFinaliseAccessPermission()));
  then
    $outcome.setSuccess(true);
end

rule "Command - Rule for Update Pet Form for Defendant"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.update-pet-form-for-defendant");
    eval(userAndGroupProvider.hasPermission($action, PermissionRuleConstants.petFormGrantAccessPermission()));
  then
    $outcome.setSuccess(true);
end