package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;
global uk.gov.moj.cpp.accesscontrol.refdata.providers.RbacProvider rbacProvider;

rule "Command - add court document for defence"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.add-court-document-for-defence");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Chambers Clerk","Chambers Admin","Defence Lawyers", "Advocates", "Court Administrators", "NCES"));
    and eval(rbacProvider.isLoggedInUserAllowedToUploadDocument($action))
  then
    $outcome.setSuccess(true);
end


