package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import java.util.ArrayList;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;
global uk.gov.moj.cpp.accesscontrol.progression.providers.ProgressionProvider progressionProvider;
global uk.gov.moj.cpp.accesscontrol.refdata.providers.RbacProvider rbacProvider;
global uk.gov.justice.api.resource.service.CourtDocumentProvider courtDocumentProvider;


rule "Query - Access control for progression.query.shared-court-documents"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.shared-court-documents");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users","Court Clerks", "Crown Court Admin", "Listing Officers", "Court Administrators", "Legal Advisers", "Magistrates"))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.courtdocument"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.courtdocument");
    eval(rbacProvider.isLoggedInUserAllowedToReadDocument(courtDocumentProvider.getDocumentTypeId($action)))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.courtdocuments"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.courtdocuments");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users","Court Clerks", "Crown Court Admin", "Listing Officers", "Court Administrators", "Legal Advisers",
     "Prison Admin", "Court Admin", "Probation Admin", "Police Admin", "Victims & Witness Care Admin", "Youth Offending Service Admin", "Magistrates", "Court Associate", "District Judge", "Probation Admin", "Judiciary", "Court Associate", "Deputies", "DJMC", "Judge", "Second Line Support"))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.courtdocuments.for.defence"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.courtdocuments.for.defence");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Chambers Clerk","Chambers Admin","Defence Lawyers", "Advocates"))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.prosecutioncase"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.prosecutioncase");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users","Court Clerks", "Crown Court Admin", "Listing Officers", "Court Administrators", "Legal Advisers", "Probation Admin", "Judiciary", "Court Associate", "Deputies", "DJMC", "Judge",
    "Youth Offending Service Admin", "Magistrates",  "District Judge", "Second Line Support"))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.prosecutioncase.caag"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.prosecutioncase.caag");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Judiciary", "Listing Officers", "Legal Advisers", "Court Associate", "Court Clerks", "NCES", "CPS", "Probation Admin", "Youth Offending Service Admin", "Court Administrators", "Crown Court Admin", "Judge", "Police Admin","Recorders","DJMC","Deputies","Victims & Witness Care Admin"))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.case-at-a-glance"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.case-at-a-glance");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users","Court Clerks", "Crown Court Admin", "Listing Officers", "Court Administrators", "Legal Advisers", "Probation Admin"))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.search-cases"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.search-cases");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Crown Court Admin", "Listing Officers", "Court Administrators", "Legal Advisers", "System Users", "Probation Admin"))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.caseprogressiondetail"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.caseprogressiondetail");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Legal Advisers", "System Users","Court Clerks", "Crown Court Admin", "Listing Officers", "Judiciary", "Case Officer", "Court Clerks", "Probation Admin"))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.cases"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.cases");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users", "Crown Court Admin", "Listing Officers", "Judiciary", "Case Officer", "Court Clerks", "Probation Admin"))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.case-by-urn"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.case-by-urn");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users","Court Clerks","Legal Advisers","System Users","CMS" , "Crown Court Admin", "Listing Officers", "Judiciary", "Case Officer", "Probation Admin"))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.defendant"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.defendant");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users","Court Clerks", "Crown Court Admin", "Listing Officers", "Judiciary", "Case Officer", "Court Clerks"))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.defendants"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.defendants");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users" ,"Court Clerks",  "Crown Court Admin", "Listing Officers", "Judiciary", "Case Officer", "Court Clerks"))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.defendant.document"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.defendant.document");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Crown Court Admin", "Listing Officers", "Judiciary", "Case Officer", "Court Clerks"))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.crown-court.magistrate-courts"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.crown-court.magistrate-courts");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Crown Court Admin", "Listing Officers", "Judiciary", "Case Officer", "Court Clerks"))
  then
    $outcome.setSuccess(true);
end


rule "progression - Query - API - Cases defendant offences"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.defendant-offences");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Crown Court Admin", "Listing Officers", "Judiciary", "Case Officer","Court Clerks"))
  then
    $outcome.setSuccess(true);
end

rule "progression - Query - API - search by material id"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.cases-search-by-material-id");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users", "Crown Court Admin", "Listing Officers", "Judiciary", "Case Officer"))
  then
    $outcome.setSuccess(true);
end

rule "progression - Query - API - search for users groups by material id"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.usergroups-by-material-id");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users"))
  then
    $outcome.setSuccess(true);
end

rule "progression - Query - API - material-metadata"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.material-metadata");
    $allowedGroups: ArrayList() from collect(String() from progressionProvider.getAllowedUserGroups($action));
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,$allowedGroups));
  then
    $outcome.setSuccess(true);
end

rule "progression - Query - API - material-content"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.material-content");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users" ,"Court Clerks",  "Crown Court Admin", "Listing Officers", "Judiciary", "Case Officer", "Court Clerks", "Legal Advisers", "District Judge", "Court Associate", "Defence Users", "Probation Admin", "Youth Offending Service Admin", "Magistrates","Court Administrators", "Probation Admin", "Second Line Support", "Deputies", "DJMC"))
  then
    $outcome.setSuccess(true);
end

rule "progression - Query - API - material-content for defence"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.material-content-for-defence");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Chambers Clerk","Chambers Admin","Defence Lawyers", "Advocates"))
  then
    $outcome.setSuccess(true);
end

rule "progression - Query - API - court-extract"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.court-extract");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users", "Crown Court Admin", "Listing Officers", "Judiciary", "Case Officer"))
  then
    $outcome.setSuccess(true);
end

rule "progression - Query - API - eject-case"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.eject-case");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Eject Case Group","System Users", "Crown Court Admin", "Listing Officers", "Judiciary", "Case Officer"))
  then
    $outcome.setSuccess(true);
end

rule "progression - Query - API - application-extract"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.court-extract-application");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users", "Crown Court Admin", "Listing Officers", "Judiciary", "Case Officer"))
  then
    $outcome.setSuccess(true);
end

rule "progression - Query - API - defendant-request"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.defendant-request");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users", "Crown Court Admin", "Listing Officers", "Judiciary", "Case Officer"))
  then
    $outcome.setSuccess(true);
end

rule "progression - Query - API - progression.query.material-nows-content"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.material-nows-content");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users", "Listing Officers", "Court Clerks", "Legal Advisers", "Prison Admin", "Probation Admin", "Police Admin", "Victims & Witness Care Admin",
    "Youth Offending Service Admin", "Legal Aid Agency Admin", "Probation Admin", "Deputies", "DJMC" ))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.application"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.application");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users","Court Clerks", "Crown Court Admin", "Listing Officers", "Court Administrators", "Legal Advisers", "Probation Admin", "Second Line Support"))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.application.aaag"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.application.aaag");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Judiciary", "Listing Officers", "Legal Advisers", "Court Associate", "Court Clerks", "NCES", "CPS", "Probation Admin", "Youth Offending Service Admin",
     "Court Administrators", "Crown Court Admin", "Judge","Victims & Witness Care Admin","Police Admin","Recorders","DJMC","Deputies"))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.application.summary"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.application.summary");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users","Court Clerks", "Crown Court Admin", "Listing Officers", "Court Administrators", "Legal Advisers", "Probation Admin", "Second Line Support"))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.hearing"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.hearing");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users","Court Clerks", "Crown Court Admin", "Listing Officers", "Court Administrators", "Legal Advisers", "Judiciary", "Court Associate"))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.application.notification-status"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.application.notification-status");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users","Court Clerks", "Crown Court Admin", "Listing Officers", "Court Administrators", "Legal Advisers", "Probation Admin"))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.prosecution.notification-status"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.prosecution.notification-status");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users","Court Clerks", "Crown Court Admin", "Listing Officers", "Court Administrators", "Legal Advisers", "Probation Admin"))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.associated-organisation"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.associated-organisation");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users", "Defence Users", "Court Clerks", "Court Administrators", "Crown Court Admin", "Listing Officers", "Legal Advisers", "Judiciary", "Court Associate", "Deputies", "DJMC", "Judge"))
  then
    $outcome.setSuccess(true);
end

rule "Command - Access all case notes for progression.query.case-notes"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.case-notes");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Crown Court Admin", "Listing Officers", "Court Administrators", "Legal Advisers", "Judiciary"));
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.defendants-by-laacontractnumber"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.defendants-by-laacontractnumber");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users", "Defence Users", "Court Clerks", "Court Administrators", "Crown Court Admin", "Listing Officers", "Legal Advisers"))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.partial-match-defendants"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.partial-match-defendants");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users", "Court Admin", "Court Associate", "Court Clerk", "Listing Officers", "Legal Advisers"))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.case-lsm-info"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.case-lsm-info");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Judiciary", "Listing Officers", "Legal Advisers", "Court Associate","Court Clerks", "NCES", "CPS", "Probation Admin", "Youth Offending Service Admin", "Court Administrators", "Crown Court Admin", "Judge","Police Admin","Recorders","DJMC","Deputies","Victims & Witness Care Admin"))
  then
    $outcome.setSuccess(true);
end

rule "progression - Query - API - progression.query.now-document-requests-by-request-id"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.now-document-requests-by-request-id");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users", "Listing Officers", "Court Clerks", "Legal Advisers", "Prison Admin", "Probation Admin", "Police Admin", "Victims & Witness Care Admin", "Youth Offending Service Admin", "Legal Aid Agency Admin", "Probation Admin"))
  then
    $outcome.setSuccess(true);
end

rule "progression - Query - API - progression.query.now-document-request-by-hearing"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.now-document-request-by-hearing");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users", "Listing Officers", "Court Clerks", "Legal Advisers", "Prison Admin", "Probation Admin", "Police Admin", "Victims & Witness Care Admin", "Youth Offending Service Admin", "Legal Aid Agency Admin", "Probation Admin"))
  then
    $outcome.setSuccess(true);
end

rule "progression - Query - API - progression.query.informant-register-document-request"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.informant-register-document-request");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users", "Listing Officers", "Court Clerks", "Legal Advisers", "Prison Admin", "Probation Admin", "Police Admin", "Victims & Witness Care Admin", "Youth Offending Service Admin", "Legal Aid Agency Admin", "Probation Admin"))
  then
    $outcome.setSuccess(true);
end

rule "progression - Query - API - progression.query.informant-register-document-by-material"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.informant-register-document-by-material");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users", "Listing Officers", "Court Clerks", "Legal Advisers", "Prison Admin", "Probation Admin", "Police Admin", "Victims & Witness Care Admin",
    "Youth Offending Service Admin", "Legal Aid Agency Admin", "Probation Admin"))
  then
    $outcome.setSuccess(true);
end

rule "progression - Query - API - progression.query.informant-register-document-by-request-date"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.informant-register-document-by-request-date");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users", "Listing Officers", "Court Clerks", "Legal Advisers", "Prison Admin", "Probation Admin", "Police Admin", "Victims & Witness Care Admin",
    "Youth Offending Service Admin", "Legal Aid Agency Admin", "Probation Admin"))
  then
    $outcome.setSuccess(true);
end

rule "progression - Query - API - progression.query.court-register-document-request"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.court-register-document-request");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users", "Listing Officers", "Court Clerks", "Legal Advisers", "Prison Admin", "Probation Admin", "Police Admin", "Victims & Witness Care Admin",
    "Youth Offending Service Admin", "Legal Aid Agency Admin", "Probation Admin"))
  then
    $outcome.setSuccess(true);
end

rule "progression - Query - API - progression.query.court-register-document-by-material"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.court-register-document-by-material");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users", "Listing Officers", "Court Clerks", "Legal Advisers", "Prison Admin", "Probation Admin", "Police Admin", "Victims & Witness Care Admin",
    "Youth Offending Service Admin", "Legal Aid Agency Admin", "Probation Admin"))
  then
    $outcome.setSuccess(true);
end

rule "progression - Query - API - progression.query.court-register-document-by-request-date"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.court-register-document-by-request-date");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users", "Listing Officers", "Court Clerks", "Legal Advisers", "Prison Admin", "Probation Admin", "Police Admin", "Victims & Witness Care Admin",
    "Youth Offending Service Admin", "Legal Aid Agency Admin", "Probation Admin"))
  then
    $outcome.setSuccess(true);
end

rule "progression - Query - API - progression.query.prison-court-register-document-by-court-centre"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.prison-court-register-document-by-court-centre");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users", "Listing Officers", "Court Clerks", "Legal Advisers", "Prison Admin", "Probation Admin", "Police Admin", "Victims & Witness Care Admin",
    "Youth Offending Service Admin", "Legal Aid Agency Admin", "Probation Admin"))
  then
    $outcome.setSuccess(true);
end