package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import java.util.Arrays;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;



rule "Query - Access control for  progression.query.caseprogressiondetail"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.caseprogressiondetail");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System Users", "Court Operations Officers", "Listing Officers", "Judiciary")))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.cases"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.cases");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System Users", "Court Operations Officers", "Listing Officers", "Judiciary")))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.defendant"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.defendant");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System Users", "Court Operations Officers", "Listing Officers", "Judiciary")))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.defendants"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.defendants");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System Users", "Court Operations Officers", "Listing Officers", "Judiciary")))
  then
    $outcome.setSuccess(true);
end

rule "Query - Access control for  progression.query.crown-court.magistrate-courts"
  when
    $outcome: Outcome();
    $action: Action(name == "progression.query.crown-court.magistrate-courts");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, Arrays.asList("System Users", "Court Operations Officers", "Listing Officers", "Judiciary")))
  then
    $outcome.setSuccess(true);
end