#%RAML 0.8
title: RAML for events listened by lifecycle event processor
baseUri: message://event/processor/message/progression

version: v1
/public.event:
  post:
      body:
# ***** Deprecated API - Start ********
# ***** Do not add any new API in this section *****
          application/vnd.material.material-added+json:
              schema: !include json/schema/material.material-added.json
              example: !include json/material.material-added.json

          application/vnd.public.progression.case-document-added+json:
              schema: !include json/schema/public.progression.case-document-added.json
              example: !include json/public.progression.case-document-added.json

            ############  Listing Start ############

          application/vnd.public.listing.case-sent-for-listing+json:
              schema: !include json/schema/public.listing.case-sent-for-listing.json
              example: !include json/public.listing.case-sent-for-listing.json
          application/vnd.public.listing.hearing-confirmed+json:
              schema: !include json/schema/public.listing.hearing-confirmed.json
              example: !include json/public.listing.hearing-confirmed.json
          application/vnd.public.listing.hearing-updated+json:
              schema: !include json/schema/public.listing.hearing-updated.json
              example: !include json/public.listing.hearing-updated.json

            ############  Listing End ############

            ############  Hearing Start ############

          application/vnd.public.hearing.adjourned+json:
              schema: !include json/schema/public.hearing.adjourned.json
              example: !include json/public.hearing.adjourned.json
          application/vnd.public.hearing.offence-conviction-date-changed+json:
              schema: !include json/schema/public.hearing.offence-conviction-date-changed.json
              example: !include json/public.hearing.offence-conviction-date-changed.json
          application/vnd.public.hearing.offence-conviction-date-removed+json:
              schema: !include json/schema/public.hearing.offence-conviction-date-removed.json
              example: !include json/public.hearing.offence-conviction-date-removed.json
          application/vnd.public.hearing.resulted+json:
              schema: !include json/schema/public.hearing.resulted.json
              example: !include json/public.hearing.resulted.json

          application/vnd.public.hearing.now-document-requested+json:
              schema: !include json/schema/public.hearing.now-document-requested.json
              example: !include json/public.hearing.now-document-requested.json

             ############  Hearing End ############

            ############ Print starts#########

          application/vnd.public.notificationnotify.events.notification-failed+json:
                schema: !include json/schema/public.notificationnotify.events.notification-failed.json
                example: !include json/public.notificationnotify.events.notification-failed.json
          application/vnd.public.notificationnotify.events.notification-sent+json:
                schema: !include json/schema/public.notificationnotify.events.notification-sent.json
                example: !include json/public.notificationnotify.events.notification-sent.json

            ############ Print ends #########
/progression.event:
  post:
    body:
        application/vnd.progression.event.prosecution-case-defendant-updated+json:
            example: !include json/progression.event.prosecution-case-defendant-updated.json
            schema: !include json/schema/progression.event.prosecution-case-defendant-updated.json
        application/vnd.progression.event.court-document-added+json:
            example: !include json/progression.event.court-document-added.json
            schema: !include json/schema/progression.event.court-document-added.json
        application/vnd.progression.event.court-document-uploaded+json:
            example: !include json/progression.event.court-document-uploaded.json
            schema: !include json/schema/progression.event.court-document-uploaded.json
        application/vnd.progression.event.court-document-removed+json:
            example: !include json/progression.event.court-document-removed.json
            schema: !include json/schema/progression.event.court-document-removed.json
        application/vnd.progression.event.defendant-bail-document-created+json:
            example: !include json/progression.event.defendant-bail-document-created.json
            schema: !include json/schema/progression.event.defendant-bail-document-created.json
        application/vnd.progression.events.offences-for-defendant-changed+json:
            example: !include json/progression.events.offences-for-defendant-changed.json
            schema: !include json/schema/progression.events.offences-for-defendant-changed.json
        application/vnd.progression.event.print-requested+json:
            example: !include json/progression.event.print-requested.json
            schema: !include json/schema/progression.event.print-requested.json
        application/vnd.progression.event.email-requested+json:
            example: !include json/progression.event.email-requested.json
            schema: !include json/schema/progression.event.email-requested.json
        application/vnd.progression.event.summons-data-prepared+json:
            example: !include json/progression.event.summons-data-prepared.json
            schema: !include json/schema/progression.event.summons-data-prepared.json
        application/vnd.progression.event.nows-material-request-recorded+json:
            schema: !include json/schema/progression.event.nows-material-request-recorded.json
            example: !include json/progression.event.nows-material-request-recorded.json
        application/vnd.progression.event.nows-material-status-updated+json:
            schema: !include json/schema/progression.event.nows-material-status-updated.json
            example: !include json/progression.event.nows-material-status-updated.json
        application/vnd.progression.hearing-initiate-enriched+json:
            schema: !include json/schema/progression.event-hearing-initiate-enriched.json
            example: !include json/progression.event-hearing-initiate-enriched.json
        application/vnd.progression.event.court-application-created+json:
            schema: !include json/schema/progression.event.court-application-created.json
            example: !include json/progression.event.court-application-created.json
        application/vnd.progression.event.court-application-updated+json:
            schema: !include json/schema/progression.event.court-application-updated.json
            example: !include json/progression.event.court-application-updated.json
        application/vnd.progression.event.court-application-rejected+json:
            schema: !include json/schema/progression.event.court-application-rejected.json
            example: !include json/progression.event.court-application-rejected.json
        application/vnd.progression.event.court-proceedings-initiated+json:
            schema: !include json/schema/progression.event.court-proceedings-initiated.json
            example: !include json/progression.event.court-proceedings-initiated.json
        application/vnd.progression.event.listed-court-application-changed+json:
            example: !include json/progression.event.listed-court-application-changed.json
            schema: !include json/schema/progression.event.listed-court-application-changed.json
        application/vnd.progression.event.application-referred-to-court+json:
            schema: !include json/schema/progression.event.application-referred-to-court.json
            example: !include json/progression.event.application-referred-to-court.json
        application/vnd.progression.event.hearing-extended+json:
            schema: !include json/schema/progression.event.hearing-extended.json
            example: !include json/progression.event.hearing-extended.json
        application/vnd.progression.event.defendants-added-to-court-proceedings+json:
            schema: !include json/schema/progression.event.defendants-added-to-court-proceedings.json
            example: !include json/progression.event.defendants-added-to-court-proceedings.json

  ############  Association Start ############

        application/vnd.progression.event.defence-organisation-associated+json:
            schema: !include json/schema/progression.event.defence-organisation-associated.json
            example: !include json/progression.event.defence-organisation-associated.json
        application/vnd.progression.event.defence-organisation-disassociated+json:
            schema: !include json/schema/progression.event.defence-organisation-disassociated.json
            example: !include json/progression.event.defence-organisation-disassociated.json
  ############  Association End ############


# ***** Deprecated API - Start ********
# ***** Do not add any new API in this section *****
        application/vnd.progression.event.cases-referred-to-court+json:
            example: !include json/progression.event.cases-referred-to-court.json
            schema: !include json/schema/progression.event.cases-referred-to-court.json
        application/vnd.progression.events.new-case-document-received+json:
            example: !include json/progression.events.new-case-document-received.json
            schema: !include json/schema/progression.events.new-case-document-received.json
        application/vnd.progression.events.sentence-hearing-date-added+json:
            schema: !include json/schema/progression.events.sentence-hearing-date-added.json
            example: !include json/progression.events.sentence-hearing-date-added.json
        application/vnd.progression.events.case-added-to-crown-court+json:
            schema: !include json/schema/progression.events.case-added-to-crown-court.json
            example: !include json/progression.events.case-added-to-crown-court.json
        application/vnd.progression.events.offences-for-defendant-updated+json:
            schema: !include json/schema/progression.events.offences-for-defendant-updated.json
            example: !include json/progression.events.offences-for-defendant-updated.json
        application/vnd.progression.events.defendant-offences-does-not-have-required-modeoftrial+json:
            schema: !include json/schema/progression.events.defendant-offences-does-not-have-required-modeoftrial.json
            example: !include json/progression.events.defendant-offences-does-not-have-required-modeoftrial.json
        application/vnd.progression.events.defendant-addition-failed+json:
            schema: !include json/schema/progression.events.defendant-addition-failed.json
            example: !include json/progression.events.defendant-addition-failed.json
        application/vnd.progression.events.defendant-added+json:
            schema: !include json/schema/progression.events.defendant-added.json
            example: !include json/progression.events.defendant-added.json
        application/vnd.progression.events.defendant-updated+json:
            schema: !include json/schema/progression.events.defendant-updated.json
            example: !include json/progression.events.defendant-updated.json
        application/vnd.progression.events.sending-sheet-completed+json:
            schema: !include json/schema/progression.events.sending-sheet-completed.json
            example: !include json/progression.events.sending-sheet-completed.json
        application/vnd.progression.events.sending-sheet-previously-completed+json:
            schema: !include json/schema/progression.events.sending-sheet-previously-completed.json
            example: !include json/progression.events.sending-sheet-previously-completed.json
        application/vnd.progression.events.sending-sheet-invalidated+json:
            schema: !include json/schema/progression.events.sending-sheet-invalidated.json
            example: !include json/progression.events.sending-sheet-invalidated.json

# Deprecated API  - End

