#%RAML 0.8
title: API Using media type in the URL
baseUri: message://event/processor/message/progression

/public.event:
  get:
      responses:
          200:
              body:
                    application/vnd.public.progression.events.court-document-uploaded+json:
                        schema: !include json/schema/public.progression.events.court-document-uploaded.json
                        example: !include json/public.progression.events.court-document-uploaded.json
                    application/vnd.public.progression.events.court-document-removed+json:
                        schema: !include json/schema/public.progression.events.court-document-removed.json
                        example: !include json/public.progression.events.court-document-removed.json
                    application/vnd.public.progression.prosecution-cases-referred-to-court+json:
                        schema: !include json/schema/public.progression.prosecution-cases-referred-to-court.json
                        example: !include json/public.progression.prosecution-cases-referred-to-court.json
                    application/vnd.public.progression.refer-prosecution-cases-to-court-rejected+json:
                        schema: !include json/schema/public.progression.refer-prosecution-cases-to-court-rejected.json
                        example: !include json/public.progression.refer-prosecution-cases-to-court-rejected.json
                    application/vnd.public.progression.case-defendant-changed+json:
                        schema: !include json/schema/public.progression.case-defendant-changed.json
                        example: !include json/public.progression.case-defendant-changed.json
                    application/vnd.public.progression.defendant-offences-changed+json:
                        schema: !include json/schema/public.progression.defendant-offences-changed.json
                        example: !include json/public.progression.defendant-offences-changed.json
                    application/vnd.public.hearing-detail-changed+json:
                        schema: !include json/schema/public.hearing-detail-changed.json
                        example: !include json/public.hearing-detail-changed.json
                    application/vnd.public.progression.court-application-created+json:
                        schema: !include json/schema/public.progression.court-application-created.json
                        example: !include json/public.progression.court-application-created.json
                    application/vnd.public.progression.court-application-rejected+json:
                        schema: !include json/schema/public.progression.court-application-rejected.json
                        example: !include json/public.progression.court-application-rejected.json
                    application/vnd.public.progression.events.hearing-extended+json:
                        schema: !include json/schema/public.progression.events.hearing-extended.json
                        example: !include json/public.progression.events.hearing-extended.json
                    application/vnd.public.progression.court-application-changed+json:
                        schema: !include json/schema/public.progression.court-application-changed.json
                        example: !include json/public.progression.court-application-changed.json
                    application/vnd.public.progression.court-application-updated+json:
                        schema: !include json/schema/public.progression.court-application-updated.json
                        example: !include json/public.progression.court-application-updated.json
                    application/vnd.public.progression.defendants-added-to-court-proceedings+json:
                        schema: !include json/schema/progression.event.defendants-added-to-court-proceedings.json
                        example: !include json/progression.event.defendants-added-to-court-proceedings.json
                    application/vnd.public.progression.events.case-or-application-ejected+json:
                        schema: !include json/schema/public.progression.events.case-or-application-ejected.json
                        example: !include json/public.progression.events.case-or-application-ejected.json
                    application/vnd.public.progression.boxwork-application-referred+json:
                        schema: !include json/schema/public.progression.boxwork-application-referred.json
                        example: !include json/public.progression.boxwork-application-referred.json
                    application/vnd.public.progression.boxwork-assignment-changed+json:
                        schema: !include json/schema/public.progression.boxwork-assignment-changed.json
                        example: !include json/public.progression.boxwork-assignment-changed.json
                    application/vnd.public.progression.defendant-financial-means-deleted+json:
                        schema: !include json/schema/progression.event.financial-means-deleted.json
                        example: !include json/progression.event.financial-means-deleted.json
                    application/vnd.public.progression.defence-organisation-associated+json:
                        schema: !include json/schema/progression.event.defence-organisation-associated.json
                        example: !include json/progression.event.defence-organisation-associated.json
                    application/vnd.public.progression.defence-organisation-disassociated+json:
                        schema: !include json/schema/progression.event.defence-organisation-disassociated.json
                        example: !include json/progression.event.defence-organisation-disassociated.json

# ***** Deprecated API - Start ********
# ***** Do not add any new API in this section *****
                    application/vnd.public.progression.events.sentence-hearing-date-added+json:
                        schema: !include json/schema/public.progression.events.sentence-hearing-date-added.json
                        example: !include json/public.progression.events.sentence-hearing-date-added.json
                    application/vnd.public.progression.case-document-added+json:
                        schema: !include json/schema/public.progression.case-document-added.json
                        example: !include json/public.progression.case-document-added.json
                    application/vnd.public.progression.events.case-added-to-crown-court+json:
                        schema: !include json/schema/public.progression.events.case-added-to-crown-court.json
                        example: !include json/public.progression.events.case-added-to-crown-court.json
                    application/vnd.public.progression.events.case-already-exists-in-crown-court+json:
                        schema: !include json/schema/public.progression.events.case-already-exists-in-crown-court.json
                        example: !include json/public.progression.events.case-already-exists-in-crown-court.json
                    application/vnd.public.progression.events.offences-for-defendant-updated+json:
                        schema: !include json/schema/public.progression.events.offences-for-defendant-updated.json
                        example: !include json/public.progression.events.offences-for-defendant-updated.json
                    application/vnd.public.progression.events.defendant-offences-does-not-have-required-modeoftrial+json:
                        schema: !include json/schema/public.progression.events.defendant-offences-does-not-have-required-modeoftrial.json
                        example: !include json/public.progression.events.defendant-offences-does-not-have-required-modeoftrial.json
                    application/vnd.public.progression.defendant-addition-failed+json:
                        schema: !include json/schema/public.progression.defendant-addition-failed.json
                        example: !include json/public.progression.defendant-addition-failed.json
                    application/vnd.public.progression.defendant-added+json:
                        schema: !include json/schema/public.progression.defendant-added.json
                        example: !include json/public.progression.defendant-added.json
                    application/vnd.public.progression.events.defendant-updated+json:
                        schema: !include json/schema/public.progression.events.defendant-updated.json
                        example: !include json/public.progression.events.defendant-updated.json
                    application/vnd.public.progression.events.sending-sheet-completed+json:
                        schema: !include json/schema/public.progression.events.sending-sheet-completed.json
                        example: !include json/public.progression.events.sending-sheet-completed.json
                    application/vnd.public.progression.events.sending-sheet-previously-completed+json:
                        schema: !include json/schema/public.progression.events.sending-sheet-previously-completed.json
                        example: !include json/public.progression.events.sending-sheet-previously-completed.json
                    application/vnd.public.progression.events.sending-sheet-invalidated+json:
                        schema: !include json/schema/public.progression.events.sending-sheet-invalidated.json
                        example: !include json/public.progression.events.sending-sheet-invalidated.json
# Deprecated API  - End
