#%RAML 0.8
title: API Using media type in the URL
baseUri: message://event/processor/message/progression

/public.event:
  get:
      responses:
          200:
              body:
                    application/vnd.public.progression.events.sentence-hearing-date-added+json:
                        schema: !include json/schema/public.progression.events.sentence-hearing-date-added.json
                        example: !include json/public.progression.events.sentence-hearing-date-added.json
                    application/vnd.public.progression.case-document-added+json:
                        schema: !include json/schema/public.progression.case-document-added.json
                        example: !include json/public.progression.case-document-added.json