#%RAML 0.8
title: RAML for events listened by lifecycle event processor
baseUri: message://event/processor/message/progression

version: v1
/public.event:
  post:
      body:
          application/vnd.material.material-added+json:
              schema: !include json/schema/material.material-added.json
              example: !include json/material.material-added.json


          application/vnd.public.progression.case-document-added+json:
              schema: !include json/schema/public.progression.case-document-added.json
              example: !include json/public.progression.case-document-added.json


/progression.event:
  post:
    body:
        application/vnd.progression.events.new-case-document-received+json:
           example: !include json/progression.events.new-case-document-received.json
           schema: !include json/schema/progression.events.new-case-document-received.json
        application/vnd.progression.events.sentence-hearing-date-added+json:
           schema: !include json/schema/progression.events.sentence-hearing-date-added.json
           example: !include json/progression.events.sentence-hearing-date-added.json
        application/vnd.progression.events.sentence-hearing-date-updated+json:
           schema: !include json/schema/progression.events.sentence-hearing-date-updated.json
           example: !include json/progression.events.sentence-hearing-date-updated.json
        application/vnd.progression.events.sentence-hearing-added+json:
            schema: !include json/schema/progression.events.sentence-hearing-added.json
            example: !include json/progression.events.sentence-hearing-added.json
        application/vnd.progression.events.case-added-to-crown-court+json:
            schema: !include json/schema/progression.events.case-added-to-crown-court.json
            example: !include json/progression.events.case-added-to-crown-court.json
        application/vnd.progression.events.defendant-allocation-decision-updated+json:
            schema: !include json/schema/progression.events.defendant-allocation-decision-updated.json
            example: !include json/progression.events.defendant-allocation-decision-updated.json
        application/vnd.progression.events.offences-for-defendant-updated+json:
            schema: !include json/schema/progression.events.offences-for-defendant-updated.json
            example: !include json/progression.events.offences-for-defendant-updated.json
        application/vnd.progression.events.defendant-offences-does-not-have-required-modeoftrial+json:
            schema: !include json/schema/progression.events.defendant-offences-does-not-have-required-modeoftrial.json
            example: !include json/progression.events.defendant-offences-does-not-have-required-modeoftrial.json
        application/vnd.progression.events.defendant-addition-failed+json:
              schema: !include json/schema/progression.events.defendant-addition-failed.json
              example: !include json/progression.events.defendant-addition-failed.json
        application/vnd.progression.events.defendant-added+json:
              schema: !include json/schema/progression.events.defendant-added.json
              example: !include json/progression.events.defendant-added.json
